services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 150M

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 150M

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 32M

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
